
\documentclass[a4paper]{article}

% \VignetteIndexEntry{Vignette}

\begin{document}

\title{ASSET(Association with SubSET) Package}
\maketitle

<<>>=
library(ASSET)
@

\section*{Example of h.traits}

Use the example data. Note the distribution of cases and controls.

<<Load data>>=
data(Xdata, package="ASSET")
table(Xdata$Subtype)
@
 
For illustration, let us obtain SNP level summaries for each of the 6 subtypes, treated
as a separate trait (and study) with 
all the controls being shared among the 6 "studies." A possible way to get these 
summaries is to trick \texttt{h.types} by
giving it 1 subtype at a time and passing an invalid value for \texttt{pool}.

<<Prepare heterogeneous trait summaries>>= 
tlab <- paste("T", 1:6, sep="")
snps <- c("SNP1", "SNP2", "SNP3")
adjust <- c("Age", "Sex", "EV1", "EV2")
beta <- sigma <- ncase <- ncntl <- matrix(NA, 3, 6)
for(j in 1:6)
{
	res <- h.types(Xdata, response.var="Subtype", snp.vars=snps, adj.vars=adjust
		, types.lab=tlab[j], cntl.lab="Control", pool= -1, side=2, logit=TRUE, meth = "Wald")
	ncase[ , j] <- sapply(snps, function(snp) nrow(na.omit(Xdata[Xdata$Subtype == tlab[j]
		, c("Subtype", snp, adjust)])))
	ncntl[, j] <- sapply(snps, function(snp) nrow(na.omit(Xdata[Xdata$Subtype == "Control"
		, c("Subtype", snp, adjust)])))
	beta[, j] <- res$Overall.Logistic$beta
	sigma[, j] <- res$Overall.Logistic$sd
}
rownames(beta) <- rownames(sigma) <- snps
colnames(beta) <- colnames(sigma) <- tlab
@  

Now let us call \texttt{h.traits} on these summary data. The correlation matrix can be 
specified by a diagonal \texttt{N11} matrix and an \texttt{N00} matrix reflecting all controls overlap.
We set the argument \texttt{cor.numr} to \texttt{TRUE}, so that the correlation due to shared controls
is used in the numerator to get an optimally powerful meta-analysis. p-value calculation should used
``importance sampling'', i.e. \texttt{meth.pval="IS"} when this option is set.

<<Heterogeneous Trait Analysis>>=
N11 <- diag(sapply(tlab, function(s) sum(Xdata$Subtype==s)), 6)
N00 <- matrix(sum(Xdata$Subtype == "Control"), 6, 6)
cor.list <- list(N11=N11, N00=N00,  N10=matrix(0, 6, 6), N01=matrix(0, 6, 6))

res <- h.traits(snp.vars=snps, traits.lab=tlab, beta.hat=beta, sigma.hat=sigma, ncase=ncase
			, ncntl=ncntl, cor=cor.list, cor.numr=FALSE, search=NULL, side=2, meta=TRUE
			, zmax.args=NULL, meth.pval="DLM")
 
h.summary(res)
@
Note that the one-sided results are similar to the subtype analysis results in the next section.
To see a forest plot for the results of \texttt{SNP3}, we use the h.forest function and the result
list returned by \texttt{h.traits}. We use option \texttt{p.adj=TRUE} to report Bonferroni adjusted p-values for
trait specific analysis.

<<Plot Traits>>=

traits.forest(snp.var="SNP3", traits.lab=tlab, beta.hat=beta, sigma.hat=sigma, ncase=ncase
        , ncntl=ncntl, cor=cor.list, rlist = res, level = 0.05, p.adj = TRUE, digits = 2)

@
\section*{Example of h.types}
%<<Plot Subtypes>>=
%types.forest(dat = a, response.var="PATH2", snp.var=names(a)[39], adj.vars=names(a)[3:38]
%         , types.lab = setdiff(unique(a$PATH2),"CONTROL"), cntl.lab = "CONTROL", rlist=ret, p.adj=FALSE)
%@
\end{document}

%
