
\documentclass[a4paper]{article}

% \VignetteIndexEntry{Vignette}

\begin{document}

\title{ASSET(Association with SubSET) Package}
\maketitle

<<>>=
library(ASSET)
@

\section*{Example of h.traits}

Use the example data. Note the distribution of cases and controls.

<<>>=
data(Xdata, package="ASSET")
table(Xdata$Subtype)
@
 
For illustration, let us obtain SNP level summaries for each of the 6 subtypes, treated
as a separate trait (and study) with 
all the controls being shared among the 6 "studies." A possible way to get these 
summaries is to trick \code{h.types} by
giving it 1 subtype at a time and passing an invalid value for \code{pool}.

<<>>= 
tlab <- paste("T", 1:6, sep="")
snps <- c("SNP1", "SNP2", "SNP3")
adjust <- c("Age", "Sex", "EV1", "EV2")
beta <- sd <- ncase <- ncntl <- matrix(NA, 3, 6)
for(j in 1:6)
{
	res <- h.types(Xdata, response.var="Subtype", snp.vars=snps, adj.vars=adjust
		, types.lab=tlab[j], cntl.lab="Control", pool= -1, side=2, logit=TRUE, meth = "Wald")
	ncase[ , j] <- sapply(snps, function(snp) nrow(na.omit(Xdata[Xdata$Subtype == tlab[j]
		, c("Subtype", snp, adjust)])))
	ncntl[, j] <- sapply(snps, function(snp) nrow(na.omit(Xdata[Xdata$Subtype == "Control"
		, c("Subtype", snp, adjust)])))
	beta[, j] <- res$Overall.Logistic$beta
	sd[, j] <- res$Overall.Logistic$sd
}
@  

Now let us call \code{h.traits} on these summary data. The correlation matrix can be 
specified by a diagonal \code{N11} matrix and a \code{N00} matrix reflecting all controls overlap.
We set the argument \code{cor.numr} to \code{TRUE}, so that the correlation due to shared controls
is used in the numerator to get an optimally powerful meta-analysis. p-value calculation should used
``importance sampling'', i.e. \code{meth.pval="IS"} when this option is set.
<<>>=
N11 <- diag(sapply(tlab, function(s) sum(Xdata$Subtype==s)), 6)
N00 <- matrix(sum(Xdata$Subtype == "Control"), 6, 6)
cor.list <- list(N11=N11, N00=N00,  N10=matrix(0, 6, 6), N01=matrix(0, 6, 6))

res <- h.traits(snp.vars=snps, traits.lab=tlab, beta.hat=beta, sigma.hat=sd, ncase=ncase
			, ncntl=ncntl, cor=cor.list, cor.numr=TRUE, search=NULL, side=2, meta=TRUE
			, zmax.args=NULL, meth.pval="IS")
 
h.summary(res)
@
Note that the one-sided results are similar to subtype analysis results in the next section.
To see a forest plot for the results of \code{SNP3}, we use the h.forest function and the result
list returned by \code{h.traits}.

\section*{Example of h.types}

\end{document}

%